config/routes.rb
Rails.application.routes.draw do
  
  resources :users,only:[:new,:create,:show]
  resources :sessions, only:[:new,:create,:destroy]
  resources :blogs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, length:{minimum:1,maximum:140}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,length:{maximum:30}
  validates :email, presence: true,length:{maximum:255},format:{with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
  validates :password, presence: true,length:{minimum: 6 }

  before_validation { email.downcase! }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(params.require(:blog).permit(:title,:content))
    if @blog.save
      redirect_to blogs_path,notice: "created!"
    else
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.new(params.require(:blog).permit(:title,:content))
    if @blog.save
      redirect_to blogs_path,notice: "editted!"
    else
      render edit
    end
  end


  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path,notice: "deleted"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)      
    else
      flash.now[:danger]="ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<% if @blog.errors.any?%>
  <% @blog.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>
<%= form_with(model: @blog,local: true) do |form| %>
  <%= form.label :title%>
  <%= form.text_field :title %>
  <%= form.label :content%>
  <%= form.text_field :content %>
  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<%= render "form"%>

app/views/blogs/index.html.erb
<table>
  <tr>
    <th>title</th>
    <th>content</th>
    <th>edit</th>
    <th>delete</th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.content %></td>
      <td><%= link_to "edit",edit_blog_path(blog.id) %></td>
      <td><%= link_to 'delet', blog_path(blog.id),method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to "new blog",new_blog_path%>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do|key,value|%>
      <%=  content_tag(:div,value,class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form_content">
    <%= f.label :name %>
    <%= f.text_field :name %>  
  </div>
  <div class="form_content">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="form_content">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form_content">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>